# Generated by Django 5.1.7 on 2025-03-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField(blank=True, null=True, verbose_name='Артикул')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('categoryId', models.SlugField(blank=True, max_length=300, null=True, verbose_name='ID категории')),
                ('categoryName', models.CharField(blank=True, max_length=300, null=True, verbose_name='Категория')),
                ('vendorName', models.CharField(blank=True, max_length=300, null=True, verbose_name='Производитель')),
                ('groupId', models.SlugField(blank=True, max_length=300, null=True, verbose_name='ID группы')),
                ('url', models.CharField(max_length=300, unique=True, verbose_name='Ссылка')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('shop', models.CharField(blank=True, choices=[('М.видео', 'М.видео'), ('Ситилинк', 'Ситилинк'), ('Wildberries', 'Wildberries')], max_length=30, null=True, verbose_name='Магазин')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'товар конкурента',
                'verbose_name_plural': 'товары конкурента',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Артикул товара')),
                ('name_my', models.CharField(blank=True, max_length=300, null=True, verbose_name='Товар')),
                ('price_my', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Моя цена')),
                ('shop_competitor', models.CharField(blank=True, choices=[('М.видео', 'М.видео'), ('Ситилинк', 'Ситилинк'), ('Wildberries', 'Wildberries')], max_length=30, null=True, verbose_name='Конкурент')),
                ('name_competitor', models.CharField(blank=True, max_length=300, null=True, verbose_name='Товар конкурента')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка')),
                ('price_competitor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена конкурента')),
                ('diff', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True, verbose_name='Разница')),
                ('status', models.BooleanField(blank=True, null=True, verbose_name='Моя цена ниже?')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='При добавлении нового сравнения вручную дата добавляется автоматически.', null=True, verbose_name='Дата сравнения')),
            ],
            options={
                'verbose_name': 'сравнение',
                'verbose_name_plural': 'сравнения',
            },
        ),
        migrations.CreateModel(
            name='MyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField(blank=True, null=True, verbose_name='Артикул')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('categoryId', models.SlugField(blank=True, max_length=300, null=True, verbose_name='ID категории')),
                ('categoryName', models.CharField(blank=True, max_length=300, null=True, verbose_name='Категория')),
                ('vendorName', models.CharField(blank=True, max_length=300, null=True, verbose_name='Производитель')),
                ('url', models.CharField(max_length=300, unique=True, verbose_name='Ссылка')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'мой товар',
                'verbose_name_plural': 'мои товары',
            },
        ),
    ]
