# Generated by Django 5.1.7 on 2025-04-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0002_myproduct_id_product_competitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproduct',
            name='id_product_competitor',
        ),
        migrations.AddField(
            model_name='match',
            name='id_product_competitor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Артикул конкурента'),
        ),
    ]
