# Generated by Django 5.1.7 on 2025-04-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0003_remove_myproduct_id_product_competitor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorproduct',
            name='url',
            field=models.CharField(max_length=300, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='match',
            name='id_product',
            field=models.IntegerField(blank=True, null=True, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='url',
            field=models.CharField(max_length=300, verbose_name='Ссылка'),
        ),
    ]
